package rules;
dialect  "mvel"

import com.LITRuleEngine.LITPOC.models.Event;
import com.LITRuleEngine.LITPOC.models.CMRatings;

rule "Rating below 5 for time management"
    when
        $cm: CMRatings(rating < 5 && metricName == "TIME")
        $event: Event()
    then
        modify( $event ){ setEventId(3) }
        modify( $event ){ setEventDescription("Assign Time management Related Course") }
end

rule "Rating below 5 for behaviour"
    when
        $cm: CMRatings(rating < 5 && metricName == "BEHAVIOUR")
        $event: Event()
    then
        modify( $event ){ setEventId(4) }
        modify( $event ){ setEventDescription("Assign Behaviour Related Course") }
end

rule "Rating below 5 for cleanliness"
    when
        $cm: CMRatings(rating < 5 && metricName == "CLEANLINESS")
        $event: Event()
    then
        modify( $event ){ setEventId(3) }
        modify( $event ){ setEventDescription("Assign Cleanliness Related Course") }
end
