package rules;
dialect  "mvel"

import com.LITRuleEngine.LITPOC.models.Employee;
import com.LITRuleEngine.LITPOC.models.Event;
import com.LITRuleEngine.LITPOC.models.DateKeeper;

import java.util.Date;

global Long daysDiff;

rule "New joining"
    when
        $event: Event()
        $datekeeper: DateKeeper(daysDiff == 0)
    then
        modify($event){ setEventId(1) }
        modify($event){ setEventDescription("Assign Training to new Employee") }
end

rule "6 months Refresher"
    when
        $event: Event()
        $datekeeper: DateKeeper(monthsDiff == 6)
    then
        modify($event){ setEventId(2) }
        modify($event){ setEventDescription("Assign 6 Months refresher to employee")}
end
